# Generated by Django 5.0.6 on 2026-07-01 07:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(-7.5), django.core.validators.MaxValueValidator(-6.0)])),
                ('lng', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(38.5), django.core.validators.MaxValueValidator(39.7)])),
                ('junction_name', models.CharField(blank=True, help_text='Closest named intersection (PRD §5 field)', max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('minor', 'Minor (no casualties)'), ('serious', 'Serious (injury, no fatality)'), ('fatal', 'Fatal (1+ deaths)'), ('critical', 'Critical (multiple casualties)')], db_index=True, max_length=20)),
                ('vehicle_types', models.JSONField(default=list, help_text='List of one or more vehicle types, e.g. ["bus","motorcycle"]')),
                ('reporter_type', models.CharField(choices=[('police', 'Tanzania Police Force'), ('community', 'Community member'), ('hospital', 'Hospital / EMS'), ('tanroads', 'TANROADS'), ('media', 'Media report')], default='community', max_length=20)),
                ('casualties', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)])),
                ('fatalities', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)])),
                ('injuries', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)])),
                ('description', models.TextField(blank=True)),
                ('weather', models.CharField(blank=True, max_length=60)),
                ('road_condition', models.CharField(blank=True, max_length=60)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('source_notes', models.TextField(blank=True, help_text="PRD §5: e.g. 'Reported via mobile form'")),
                ('verified', models.BooleanField(default=False, help_text='Police-verified record')),
                ('junction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='accidents.junction')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at', 'severity'], name='accidents_a_occurre_3de0aa_idx'), models.Index(fields=['lat', 'lng'], name='accidents_a_lat_a9a26e_idx')],
            },
        ),
    ]
