# Generated by Django 5.0.6 on 2026-07-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junction',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='Dar es Salaam district: Ilala, Kinondoni, Temeke, Ubungo, Kigamboni', max_length=60),
        ),
        migrations.AddIndex(
            model_name='junction',
            index=models.Index(fields=['lat', 'lng'], name='accidents_j_lat_62e500_idx'),
        ),
    ]
