# Generated by Django 5.0.6 on 2026-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_junction_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='h3_cell',
            field=models.CharField(blank=True, db_index=True, help_text='Uber H3 hex cell ID at resolution 10 (~68m). Auto-set on save.', max_length=20),
        ),
        migrations.AddField(
            model_name='junction',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe identifier. Auto-generated from name on save.', max_length=120),
        ),
    ]
