# Generated by Django 5.0.6 on 2026-07-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_demo_data', models.BooleanField(default=True, help_text='When ON, demo records appear alongside real data. When OFF, only real data is shown.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='accident',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo/seed record — hidden from public when demo data is toggled off'),
        ),
        migrations.AddField(
            model_name='junction',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo/seed junction — hidden from public when demo data is toggled off'),
        ),
    ]
