# Generated by Django 5.0.6 on 2026-07-02 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0008_demo_data_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Google profile picture — auto-set on login', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supabase_uid',
            field=models.CharField(blank=True, help_text='Supabase Auth user UUID — auto-set on first Google login', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor (Officer/TANROADS)'), ('user', 'Community User'), ('police', 'Police / TPF'), ('community', 'Community Member')], default='community', max_length=20),
        ),
    ]
