# Generated by Django 5.0.6 on 2026-07-02 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0009_alter_userprofile_options_userprofile_avatar_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Django user who submitted this report. Null = anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_accidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accident',
            name='trust_level',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('community', 'Community User'), ('verified', 'Verified Report')], db_index=True, default='anonymous', help_text='Trust level affects heatmap intensity weight.', max_length=20),
        ),
        migrations.AddField(
            model_name='accident',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who confirmed they saw this incident.'),
        ),
        migrations.CreateModel(
            name='AccidentUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='accidents.accident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_accidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accident Upvote',
                'verbose_name_plural': 'Accident Upvotes',
                'ordering': ['-created_at'],
                'unique_together': {('accident', 'user')},
            },
        ),
    ]
