# Generated by Django 5.0.6 on 2026-07-02 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0010_accident_submitted_by_accident_trust_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='official_notes',
            field=models.TextField(blank=True, help_text='Official notes added by verifying officer. Visible to public.', null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection — shown to the original submitter.', null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current verification status of this accident report.', max_length=20),
        ),
        migrations.AddField(
            model_name='accident',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when verification action was taken.', null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Editor who verified or rejected this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_accidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
