# Generated by Django 5.0.6 on 2026-07-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0011_accident_official_notes_accident_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of uploaded accident photo', max_length=500),
        ),
    ]
