# Generated by Django 5.0.6 on 2026-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0012_accident_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='district',
            field=models.CharField(blank=True, choices=[('', 'Select district'), ('Ilala', 'Ilala'), ('Kinondoni', 'Kinondoni'), ('Temeke', 'Temeke'), ('Ubungo', 'Ubungo'), ('Kigamboni', 'Kigamboni')], db_index=True, help_text='Dar es Salaam district where the accident occurred', max_length=60),
        ),
    ]
