# Generated by Django 5.0.6 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0013_accident_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='ward',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Ward (Kata) within the district. Auto-populated from location picker.',
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name='accident',
            name='location_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Canonical ID of a known location from accidents.locations (e.g. 'kigamboni-ferry-terminal').",
                max_length=120,
            ),
        ),
    ]
